### ISSUE TITLE
Crackling/static noise in Zelda : Oracle of Ages/Seasons

### ISSUE THREAD

**Issue by mic-** [MiSTer-devel/Gameboy_MiSTer#149]
This might be a duplicate of issue #102 , but I don't know for sure, so I'll let someone who is working on the core determine if that's the case:

### Environment
* Gameboy core and Main version: 20210329 (behavior wasn't introduced here, but still exists here).
* ROM hashes (SHA-256): Oracle of Ages: dbbb897a003654abfef7eadbfd401421e247e0c37319e947e5c80099f8f7ab86, Oracle of Seasons: 35fd809a21df04c7dac16cf76f7cc5d04017e3beabca102d2e378912a48539d9
* HDMI output.
* No custom audio filters.

### Step by step
While in the overworld in either game, press Select repeatedly to show/hide the world map.
Alternatively, press Start repeatedly to show/hide the item menu, or press Start to show the item menu and then press Select repeatedly to cycle between the different subscreens.

### Expected result
Clean audio output is heard.

### Actual result
Some faint crackling/static noise can be heard in the audio output.

**Comment by maij** [comment]
I experience this too with the current core version. In the Oracle of Ages, for example, at the start of the game you can't open any menus. If you press Start or Select you can hear an "access denied" type sound, but it does sound like there is some extended noise. It would be good to check this against the original hardware.

**Comment by maij** [comment]
I think this issue has been resolved at some point, though there have not been any obvious changes to the RTL.
I can no longer reproduce the static/crackling issue.

**Comment by Toryalai1** [comment]
This ticket can be closed

**Comment by rougepoubelle** [comment]
I believe I am still experiencing this issue on the current core release.

**Comment by paulb-nl** [comment]
Those crackling sounds happen on original hardware too. At least on GBA hardware.
