### ISSUE TITLE
Donkey Kong 94 freezes after first level

### ISSUE THREAD

**Issue by tofana10am** [MiSTer-devel/Gameboy_MiSTer#64]
Not sure what’s going on here, but DK 94 for GameBoy has frozen at the same point repeatedly just after clearing the first board.  DK takes Pauline up the ladders then Mario chases after her and ... nothing.  Bottom half of the screen clears out and game hangs.  Is anyone else seeing this issue?

**Comment by zerohimself** [comment]
Semi-Confirmed with"Donkey Kong (World) (Rev A) (SGB Enhanced).gb" and the japan version.
I'm not sure if this is original behavior, but it appears to have frozen.. But pressing start resumes the game. I would expect that there may be an overlay or some text missing, but I don't have an original to confirm with..

**Comment by zerohimself** [comment]
I can confirm there is a missing overlay from testing with an everdrive x7 on a GBA and GBC.
On MiSTer it seems to stop refreshing the screen in the middle of the frame, and the overlay does not appear.

**Comment by tofana10am** [comment]
Thanks!  That good to hear that the game is still playable by pressing start.  Thanks for the assist. ;)

**Comment by paulb-nl** [comment]
This is fixed by fd8383358b4640c5187333dd34357be5fc949198

**Comment by sorgelig** [comment]
game still freezes after first level 
Donkey Kong (Japan, USA) (SGB Enhanced).gb

**Comment by paulb-nl** [comment]
Works fine here with release 0622

**Comment by tofana10am** [comment]
Agreed.  Works fine with updated MAIN (0622).  Tried Successfully with both Gameboy and Gameboy Color cores.  Overlay with score appears after round and requires a button press to move on to the next round.  Thanks paulb-nl!
